/** Browser-safe configuration, transport, state, slot, and component interfaces. */
import type { ComponentType,ReactNode } from "react";
import type { QChatAction,QChatActionResult,QChatAgentEvent,QChatErrorShape,QChatMessageRecord,QChatPerformanceRecord,QChatProductVariantCatalog,QChatUIDocument } from "@qchat/core";
export interface QChatClientCapabilities { readonly attachments?:boolean; readonly dictation?:boolean; readonly modelSelection?:boolean; readonly tools?:boolean }
export type QChatAttachment = { readonly kind:"image";readonly mediaType:string;readonly dataUrl:string;readonly filename?:string } | { readonly kind:"file";readonly mediaType:string;readonly uploadId:string;readonly filename?:string };
export interface QChatAttachmentPolicy { readonly acceptedMimeTypes:readonly string[];readonly maxFiles?:number;readonly maxFileSizeBytes?:number;readonly maxVisible?:number;readonly processFile?:(file:File,options:{readonly signal:AbortSignal;readonly onProgress:(percent:number)=>void})=>Promise<QChatAttachment> }
/** Host-selected voice adapter. Recording, transcription, and speech are never assumed to exist in every browser. */
export interface QChatLiveVoiceOptions { readonly locale:string;readonly signal:AbortSignal;readonly onState:(state:"permission"|"connecting"|"listening"|"speaking"|"closed")=>void;readonly onError:(message:string)=>void;readonly onLevel?:(level:number,elapsedMs:number,device:string)=>void;readonly onMetric?:(name:string,durationMs:number)=>void }
export interface QChatVoiceAdapter { readonly connect?:(options:QChatLiveVoiceOptions)=>Promise<{close():void}>; readonly preferRecording?:boolean; readonly transcribe?:(audio:Blob,locale:string,signal:AbortSignal,onProgress?:(label:string,metric?:{readonly name:string;readonly durationMs:number})=>void)=>Promise<string>; readonly speak?:(text:string,locale:string,signal:AbortSignal,onProgress?:(label:string,metric?:{readonly name:string;readonly durationMs:number})=>void)=>Promise<void> }
export interface QChatClient { readonly capabilities:QChatClientCapabilities; run(input:{readonly messages:readonly QChatMessageRecord[];readonly attachments:readonly QChatAttachment[];readonly locale:string;readonly conversationId:string;readonly runId:string;readonly signal:AbortSignal}):AsyncIterable<QChatAgentEvent>; action(action:QChatAction):Promise<QChatActionResult> }
export interface QChatTheme { readonly accent?:string; readonly background?:string; readonly foreground?:string; readonly surface?:string; readonly muted?:string; readonly radius?:string; readonly fontFamily?:string; readonly motionScale?:number; readonly spacingUnit?:string; readonly composerSurface?:string; readonly composerBorder?:string; readonly controlSurface?:string; readonly controlForeground?:string; readonly railGap?:string; readonly railCardWidth?:string; readonly productPadding?:string; readonly productImageHeight?:string; readonly productImageRadius?:string; readonly messagePadding?:string; readonly threadGap?:string; readonly threadWidth?:string; readonly loadingImageHeight?:string; readonly voiceAccent?:string }
/** Host-owned locale metadata and chrome copy. Model-authored content is not auto-translated. */
export interface QChatLocaleDefinition { readonly code:string; readonly label:string; readonly direction:"ltr"|"rtl"; readonly fontFamily?:string }
export type QChatTranslationKey = "thinking"|"thoughtFor"|"second"|"seconds"|"loadingProducts"|"color"|"size"|"chooseAvailable"|"previousProducts"|"nextProducts"|"sendMessage"|"stopGeneration"|"addImage"|"startVoiceMode"|"examplePrompts"|"messagePlaceholder"|"you"|"read"|"startDictation"|"stopDictation"|"exitVoiceMode"|"listening"|"speaking";
export type QChatTranslations = Readonly<Record<QChatTranslationKey,string>>;
export interface QChatLocalization { readonly locale?:string; readonly defaultLocale?:string; readonly locales?:readonly QChatLocaleDefinition[]; readonly translations?:Readonly<Record<string,Partial<QChatTranslations>>> }
export interface QChatSlotProps { readonly children?:ReactNode; readonly className?:string }
/** Trusted host-authored UI. The model cannot choose its component or data. */
export interface QChatHostView { readonly render:()=>ReactNode }
export interface QChatSlots { readonly composer?:ComponentType<QChatSlotProps>; readonly thread?:ComponentType<QChatSlotProps>; readonly message?:ComponentType<{readonly message:QChatMessageRecord}>; readonly userAvatar?:ComponentType; readonly assistantAvatar?:ComponentType; readonly thinking?:ComponentType<QChatSlotProps>; readonly toolActivity?:ComponentType<QChatSlotProps>; readonly loading?:ComponentType; readonly error?:ComponentType<{error:QChatErrorShape}> }
export interface QChatConfig { readonly telemetry?:{readonly onRecord?:(record:QChatPerformanceRecord)=>void;readonly slowThresholdMs?:number}; readonly theme?:QChatTheme; readonly localization?:QChatLocalization; readonly attachments?:QChatAttachmentPolicy; readonly voice?:QChatVoiceAdapter; readonly slots?:QChatSlots; readonly hostView?:QChatHostView; readonly productVariants?:QChatProductVariantCatalog }
export interface QChatToolState { readonly id:string; readonly name:string; readonly status:"running"|"complete"|"error"; readonly summary?:string }
export interface QChatStoreState { readonly messages:readonly QChatMessageRecord[]; readonly draft:string; readonly attachments:readonly QChatAttachment[]; readonly locale:string; readonly status:"idle"|"running"|"error"; readonly reasoning?:{readonly label:string;readonly startedAt:number;readonly elapsedMs:number}; readonly tools:readonly QChatToolState[]; readonly document?:QChatUIDocument; readonly generatingUI:boolean; readonly error?:QChatErrorShape; readonly performance:readonly QChatPerformanceRecord[]; readonly selections:Readonly<Record<string,string>>; recordPerformance(record:QChatPerformanceRecord):void; setDraft(value:string):void; setAttachments(value:readonly QChatAttachment[]):void; setLocale(value:string):void; submit():Promise<void>; cancel():void; dispatchAction(action:Omit<QChatAction,"conversationId"|"runId">):Promise<QChatActionResult>; select(key:string,value:string):void }
export interface QChatProviderProps { readonly client:QChatClient; readonly config?:QChatConfig; readonly initialMessages?:readonly QChatMessageRecord[]; readonly initialDocument?:QChatUIDocument; readonly initialTools?:readonly QChatToolState[]; readonly conversationId?:string; readonly children:ReactNode }
