/** Browser-safe configuration, transport, state, slot, and component interfaces. */
import type { ComponentType,ReactNode } from "react";
import type { QChatAction,QChatActionResult,QChatAgentEvent,QChatErrorShape,QChatMessageRecord,QChatPerformanceRecord,QChatUIDocument } from "@qchat/core";
export interface QChatClientCapabilities { readonly attachments?:boolean; readonly dictation?:boolean; readonly modelSelection?:boolean; readonly tools?:boolean }
export interface QChatClient { readonly capabilities:QChatClientCapabilities; run(input:{readonly messages:readonly QChatMessageRecord[];readonly conversationId:string;readonly runId:string;readonly signal:AbortSignal}):AsyncIterable<QChatAgentEvent>; action(action:QChatAction):Promise<QChatActionResult> }
export interface QChatTheme { readonly accent?:string; readonly background?:string; readonly foreground?:string; readonly surface?:string; readonly muted?:string; readonly radius?:string; readonly fontFamily?:string; readonly motionScale?:number }
export interface QChatSlotProps { readonly children?:ReactNode; readonly className?:string }
export interface QChatSlots { readonly composer?:ComponentType<QChatSlotProps>; readonly thread?:ComponentType<QChatSlotProps>; readonly userAvatar?:ComponentType; readonly assistantAvatar?:ComponentType; readonly thinking?:ComponentType<QChatSlotProps>; readonly toolActivity?:ComponentType<QChatSlotProps>; readonly loading?:ComponentType; readonly error?:ComponentType<{error:QChatErrorShape}> }
export interface QChatConfig { readonly theme?:QChatTheme; readonly slots?:QChatSlots }
export interface QChatToolState { readonly id:string; readonly name:string; readonly status:"running"|"complete"|"error"; readonly summary?:string }
export interface QChatStoreState { readonly messages:readonly QChatMessageRecord[]; readonly draft:string; readonly status:"idle"|"running"|"error"; readonly reasoning?:{readonly label:string;readonly startedAt:number;readonly elapsedMs:number}; readonly tools:readonly QChatToolState[]; readonly document?:QChatUIDocument; readonly generatingUI:boolean; readonly error?:QChatErrorShape; readonly performance:readonly QChatPerformanceRecord[]; readonly selections:Readonly<Record<string,string>>; setDraft(value:string):void; submit():Promise<void>; cancel():void; dispatchAction(action:Omit<QChatAction,"conversationId"|"runId">):Promise<QChatActionResult>; select(key:string,value:string):void }
export interface QChatProviderProps { readonly client:QChatClient; readonly config?:QChatConfig; readonly initialMessages?:readonly QChatMessageRecord[]; readonly conversationId?:string; readonly children:ReactNode }
