"use client";
import {useEffect,useState} from "react";
import {useQChatConfig,useQChatLocale,useQChatPerformance,useQChatRunState} from "@qchat/react";
export function PerformancePanel(){
  const records=useQChatPerformance();const {status,error}=useQChatRunState();const {locale}=useQChatLocale();const config=useQChatConfig();const [elapsed,setElapsed]=useState(0);const ar=locale.code.startsWith("ar");const threshold=config.telemetry?.slowThresholdMs??5000;
  useEffect(()=>{if(status!=="running")return;const start=performance.now();queueMicrotask(()=>setElapsed(0));const timer=setInterval(()=>setElapsed(performance.now()-start),500);return()=>clearInterval(timer)},[status]);
  const current=records.slice(-60);
  return <details className="qchat-diagnostics"><summary>{ar?"التشخيص والأداء":"Diagnostics"}{status==="running"?` · ${(elapsed/1000).toFixed(1)}s`:""}{status==="running"&&elapsed>threshold?` · ${ar?"استجابة بطيئة":"Slow response"}`:""}{error?` · ${error.code}`:""}</summary><div className="qchat-diagnostics-body"><p>{ar?"الأزمنة متداخلة، وليست أجزاءً تُجمع. زمن أول رمز من المزود يشمل الانتظار والمعالجة والشبكة؛ لا يكشف تفاصيل طابور المزود.":"Timings overlap; do not add them. Provider first-token time includes provider queue, processing and network. Internal provider queue time is not exposed."}</p>{error&&<p role="alert">{error.message}</p>}<table><thead><tr><th>{ar?"المرحلة":"Stage"}</th><th>ms</th><th>{ar?"التفاصيل":"Details"}</th></tr></thead><tbody>{current.map((record,index)=><tr key={`${record.name}-${index}`} className={record.name!=="voice.capture"&&record.durationMs>threshold?"is-slow":undefined}><td>{record.name}</td><td>{record.durationMs.toFixed(1)}</td><td>{record.attributes?.model??record.attributes?.layer??""}{record.attributes?.status?` · HTTP ${record.attributes.status}`:""}{record.name!=="voice.capture"&&record.durationMs>threshold?" · slow":""}</td></tr>)}</tbody></table><button type="button" onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(records,null,2)],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download="qchat-performance.json";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}>{ar?"تنزيل السجل":"Download timing log"}</button></div></details>;
}
