"use client";
import { useEffect, useState } from "react";
import { Check,Globe2 } from "lucide-react";
import { z } from "zod";
import { QChatProvider,QChatThread,createQChatHostView } from "@qchat/react";
import type { QChatUIDocument } from "@qchat/core";
import { ElementsComposer,ElementsMessage,ElementsThinking } from "./elements-chat-ui";
import { showcaseAttachmentPolicy,showcaseComposerRules,showcaseLocalization,showcaseProductVariants,showcaseTheme } from "./showcase-config";
import { agentClient } from "./agent-client";
import { testGraphClient } from "./test-graph-client";
import { showcaseVoice } from "./showcase-voice";
import {PerformancePanel} from "./performance-panel";
const productDocument:QChatUIDocument={version:"1",id:"shoe-results",layout:"scroll",children:[{type:"product-collection",id:"performance-shoes",direction:"horizontal",title:"Performance runners in blue",items:[{type:"product-card",id:"velocity-blue",title:"Velocity Pro 3",description:"Carbon-assisted daily trainer with responsive cushioning and a breathable mesh upper.",image:{src:"https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=900",alt:"Blue performance running shoe on a dark background"},price:{amount:189,currency:"USD"},tags:["Road","Fast"],colors:[{value:"blue",label:"Blue",color:"#3478f6"},{value:"black",label:"Black",color:"#17191e"}],sizes:[{value:"9",label:"9"},{value:"10",label:"10"},{value:"11",label:"11"}],primaryAction:{label:"Add to cart",name:"product.add",payload:{productId:"velocity-blue"}},secondaryAction:{label:"Details",name:"product.open",payload:{productId:"velocity-blue"}}},{type:"product-card",id:"aero-knit",title:"Aero Knit One",description:"Lightweight tempo shoe tuned for quick transitions and a secure midfoot feel.",image:{src:"https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/03421f93409523.5eb408a551d0a.jpg",alt:"Blue knit running shoe in studio lighting"},price:{amount:164,currency:"USD"},tags:["Tempo","Light"],colors:[{value:"royal",label:"Royal",color:"#1f5cff"},{value:"silver",label:"Silver",color:"#b9c1cb"}],sizes:[{value:"8",label:"8"},{value:"9",label:"9"},{value:"10",label:"10"}],primaryAction:{label:"Add to cart",name:"product.add",payload:{productId:"aero-knit"}},secondaryAction:{label:"Details",name:"product.open",payload:{productId:"aero-knit"}}}]}]};
const collection=productDocument.children[0];
if(collection?.type!=="product-collection")throw new Error("The showcase requires a product collection");
const first=collection.items[0]!;
const second=collection.items[1]!;
const fourCardDocument:QChatUIDocument={...productDocument,children:[{...collection,items:[
  ...collection.items,
  {...first,id:"stride-flow",title:"Stride Flow 2",description:"Cushioned everyday runner with a soft landing and flexible forefoot.",image:{src:"https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=900",alt:"Everyday running shoe"},price:{amount:139,currency:"USD"},tags:["Daily","Cushioned"],primaryAction:{label:"Add to cart",name:"product.add",payload:{productId:"stride-flow"}},secondaryAction:{label:"Details",name:"product.open",payload:{productId:"stride-flow"}}},
  {...second,id:"pace-knit",title:"Pace Knit 4",description:"A light training option for shorter runs and all-day comfort.",image:{src:"https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=900",alt:"Lightweight training shoe"},price:{amount:119,currency:"USD"},tags:["Training","Light"],primaryAction:{label:"Add to cart",name:"product.add",payload:{productId:"pace-knit"}},secondaryAction:{label:"Details",name:"product.open",payload:{productId:"pace-knit"}}}
]}]};
const initialMessages=[{id:"a",role:"assistant" as const,content:"Tell me what you are shopping for and I’ll build the controls you need.",createdAt:"2026-09-24T18:38:00.000Z"},{id:"u",role:"user" as const,content:"Show me lightweight blue running shoes under $200 with size and color options.",createdAt:"2026-09-24T18:41:00.000Z"},{id:"result",role:"assistant" as const,content:"Here are four options under $200. Choose a color and size to compare them.",createdAt:"2026-09-24T18:41:30.000Z"}];
const emailSchema=z.object({from:z.string().email(),subject:z.string().min(1),preview:z.string().min(1)});
function HostEmail({data}:{readonly data:z.infer<typeof emailSchema>}){return <div className="showcase-host-email"><span>HOST COMPONENT · EMAIL</span><h3>{data.subject}</h3><p>{data.preview}</p><small>From {data.from}</small></div>}
const emailView=createQChatHostView(HostEmail,{from:"team@example.com",subject:"Your order is on its way",preview:"Your package has shipped. Track its progress from your account."},emailSchema);
export function QChatShowcase(){
  const [hostMode,setHostMode]=useState(false);
  const [liveAvailable,setLiveAvailable]=useState(false);
  const [voiceAvailable,setVoiceAvailable]=useState(false);
  const [liveMode,setLiveMode]=useState(false);
  const [language,setLanguage]=useState<string>(showcaseComposerRules.defaultVoiceLanguage);
  const [languageOpen,setLanguageOpen]=useState(false);
  const selectedLanguage=showcaseComposerRules.voiceLanguages.find((item)=>item.code===language)??showcaseComposerRules.voiceLanguages[0]!;
  const navLabels=language.startsWith("ar")?{test:"وكيل الاختبار",live:"الوكيل المباشر",host:"واجهة المضيف",back:"العودة للدردشة"}:{test:"Test agent",live:"Live agent",host:"Host view",back:"Back to chat"};
  useEffect(()=>{fetch("/api/qchat/status").then((response)=>response.json()).then((value:unknown)=>{if(value&&typeof value==="object"){if("available" in value&&value.available===true){setLiveAvailable(true);setLiveMode(true)}if("voiceAvailable" in value&&value.voiceAvailable===true)setVoiceAvailable(true)}}).catch(()=>{});},[]);
  return <main className="showcase-shell" lang={selectedLanguage.code} dir={selectedLanguage.direction} style={{"--showcase-bg":showcaseTheme.background,"--showcase-surface":showcaseTheme.surface,"--showcase-fg":showcaseTheme.foreground,"--showcase-muted":showcaseTheme.muted} as React.CSSProperties}><section className="showcase-main">
    <header className="showcase-header"><h1>QChat</h1><div className="showcase-header-right"><div className="showcase-mode" role="group" aria-label="Agent mode"><button type="button" aria-pressed={!liveMode} onClick={()=>setLiveMode(false)}>{navLabels.test}</button><button type="button" aria-pressed={liveMode} disabled={!liveAvailable} title={liveAvailable?"Use Gemini through LangGraph":"Set GEMINI_API_KEY on the server to enable live mode"} onClick={()=>setLiveMode(true)}>{navLabels.live}</button></div><button type="button" aria-pressed={hostMode} onClick={()=>setHostMode((value)=>!value)}>{hostMode?navLabels.back:navLabels.host}</button><div className="showcase-language-wrap"><button className="showcase-language-trigger" type="button" aria-label="Choose language" aria-expanded={languageOpen} onClick={()=>setLanguageOpen((value)=>!value)}><Globe2 size={16}/><span>{language.startsWith("ar")?"AR":"EN"}</span></button>{languageOpen&&<div className="showcase-language-menu" role="group" aria-label="Chat and voice language">{showcaseComposerRules.voiceLanguages.map((item)=><button key={item.code} type="button" aria-pressed={language===item.code} onClick={()=>{setLanguage(item.code);setLanguageOpen(false)}}><span className="showcase-language-option"><span>{item.label}</span><small>{item.code}</small></span>{language===item.code&&<Check size={14} aria-hidden="true"/>}</button>)}</div>}</div></div></header>
    <div className="showcase-stage"><QChatProvider key={`${hostMode?"host":"chat"}-${liveMode?"live":"examples"}`} client={liveMode?agentClient:testGraphClient} initialMessages={hostMode?[{id:"host-intro",role:"assistant",content:"This interface is supplied by the host application. No model-generated UI is used.",createdAt:"2026-09-24T18:38:00.000Z"}]:liveMode?[]:initialMessages} initialDocument={hostMode||liveMode?undefined:fourCardDocument} config={{theme:showcaseTheme,attachments:showcaseAttachmentPolicy,voice:voiceAvailable?showcaseVoice:undefined,localization:{...showcaseLocalization,locale:language},productVariants:showcaseProductVariants,hostView:hostMode?emailView:undefined,slots:{message:ElementsMessage,thinking:ElementsThinking,toolActivity:()=>null}}}><QChatThread/><PerformancePanel/>{!hostMode&&<ElementsComposer/>}</QChatProvider></div>
  </section></main>;
}
